Update ohmyzsh and powerlevel10k

diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build b/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build
--- a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build
+++ b/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/build
@@ -9,6 +9,8 @@ if [ -n "${ZSH_VERSION:-}" ]; then
   emulate sh -o err_exit -o no_unset
 fi
 
+export LC_ALL=C
+
 usage="$(command cat <<\END
 Usage: build [-m ARCH] [-c CPU] [-d CMD] [-i IMAGE] [-s] [-w]
 
@@ -52,21 +54,32 @@ if [ "$(narg $workdir)" != 1 -o -z "${workdir##*:*}" ]; then
   exit 1
 fi
 
-appname=gitstatusd-"$gitstatus_kernel"-"$gitstatus_arch"
+appname=gitstatusd
 libgit2_tmp="$outdir"/deps/"$appname".libgit2.tmp
 
 cleanup() {
-  cd /
-  command rm -rf -- "$workdir" "$outdir"/usrbin/"$appname".tmp "$libgit2_tmp"
   trap - INT QUIT TERM ILL PIPE
+  cd /
+  if ! command rm -rf -- "$workdir" "$outdir"/usrbin/"$appname".tmp "$libgit2_tmp"; then
+    command sleep 5
+    command rm -rf -- "$workdir" "$outdir"/usrbin/"$appname".tmp "$libgit2_tmp"
+  fi
 }
 trap cleanup INT QUIT TERM ILL PIPE
 
 if [ -n "$gitstatus_install_tools" ]; then
   case "$gitstatus_kernel" in
     linux)
-      command apk update
-      command apk add binutils cmake gcc g++ git make musl-dev perl-utils
+      if command -v apk >/dev/null 2>&1; then
+        command apk update
+        command apk add binutils cmake gcc g++ git make musl-dev perl-utils
+      elif command -v apt-get >/dev/null 2>&1; then
+        apt-get update
+        apt-get install -y binutils cmake gcc g++ make wget
+      else
+        >&2 echo "[error] -s is not supported on this system"
+        exit 1
+      fi
     ;;
     freebsd)
       command pkg install -y cmake gmake binutils gcc git perl5
@@ -107,19 +120,21 @@ cpus="$(command getconf _NPROCESSORS_ONLN 2>/dev/null)" ||
   cpus=8
 
 case "$gitstatus_cpu" in
-  ppc64le)
-    archflag="-mcpu"
-  ;;
-  *)
-    archflag="-march"
-  ;;
+  powerpc64le) archflag="-mcpu";;
+  *)           archflag="-march";;
 esac
 
+cflags="$archflag=$gitstatus_cpu -fno-plt"
+
+if [ "$gitstatus_cpu" = x86-64 ]; then
+  cflags="$cflags -mtune=generic"
+fi
+
 libgit2_cmake_flags=
-libgit2_cflags="$archflag=$gitstatus_cpu"
+libgit2_cflags="$cflags"
 
 gitstatus_cxx=g++
-gitstatus_cxxflags="-I${workdir}/libgit2/include -DGITSTATUS_ZERO_NSEC -D_GNU_SOURCE $archflag=$gitstatus_cpu"
+gitstatus_cxxflags="$cflags -I${workdir}/libgit2/include -DGITSTATUS_ZERO_NSEC -D_GNU_SOURCE"
 gitstatus_ldflags="-L${workdir}/libgit2/build"
 gitstatus_ldlibs=
 gitstatus_make=make
@@ -127,14 +142,20 @@ gitstatus_make=make
 case "$gitstatus_kernel" in
   linux)
     gitstatus_ldflags="$gitstatus_ldflags -static"
+    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   freebsd)
     gitstatus_make=gmake
     gitstatus_ldflags="$gitstatus_ldflags -static"
+    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   netbsd)
     gitstatus_make=gmake
     gitstatus_ldflags="$gitstatus_ldflags -static"
+    gitstatus_ldflags="$gitstatus_ldflags -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   darwin)
     command mkdir -- "$workdir"/lib
@@ -144,12 +165,15 @@ case "$gitstatus_kernel" in
     gitstatus_cxxflags="$gitstatus_cxxflags -I/usr/local/opt/libiconv/include"
     gitstatus_ldlibs="$gitstatus_ldlibs -liconv"
     gitstatus_ldflags="$gitstatus_ldflags -L${workdir}/lib"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=OFF"
   ;;
   msys*|mingw*)
     gitstatus_ldflags="$gitstatus_ldflags -static"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   cygwin*)
     gitstatus_ldflags="$gitstatus_ldflags -static"
+    libgit2_cmake_flags="$libgit2_cmake_flags -DENABLE_REPRODUCIBLE_BUILDS=ON"
   ;;
   *)
     >&2 echo "[internal error] unhandled kernel: $gitstatus_kernel"
@@ -249,7 +273,6 @@ CFLAGS="$libgit2_cflags" command cmake \
   -DUSE_GSSAPI=OFF                     \
   -DUSE_NTLMCLIENT=OFF                 \
   -DBUILD_SHARED_LIBS=OFF              \
-  -DENABLE_REPRODUCIBLE_BUILDS=OFF     \
   $libgit2_cmake_flags                 \
   ..
 command make -j "$cpus" VERBOSE=1
@@ -267,9 +290,10 @@ app="$outdir"/usrbin/"$appname"
 command strip "$app".tmp
 
 command mkdir -- "$workdir"/repo
-command git -C "$workdir"/repo init --
+command git -C "$workdir"/repo init
+command git -C "$workdir"/repo config user.name "Your Name"
 command git -C "$workdir"/repo config user.email "you@example.com"
-command git -C "$workdir"/repo commit --allow-empty --allow-empty-message -m ''
+command git -C "$workdir"/repo commit --allow-empty --allow-empty-message --no-gpg-sign -m ''
 
 resp="$(printf "hello\037$workdir/repo\036" | "$app".tmp)"
 [ -n "$resp" -a -z "${resp##hello*1*$workdir/repo*master*}" ]
@@ -385,6 +409,7 @@ if [ -z "$gitstatus_cpu" ]; then
   case "$gitstatus_arch" in
     armv6l)         gitstatus_cpu=armv6;;
     armv7l)         gitstatus_cpu=armv7;;
+    arm64)          gitstatus_cpu=armv8;;
     aarch64)        gitstatus_cpu=armv8-a;;
     ppc64le)        gitstatus_cpu=powerpc64le;;
     riscv64)        gitstatus_cpu=rv64imafdc;;
@@ -430,9 +455,6 @@ case "$gitstatus_kernel" in
           ;;
         esac
       fi
-    elif [ -n "$gitstatus_install_tools" ]; then
-      >&2 echo '[error] -s without -d is not supported on linux'
-      exit 1
     fi
   ;;
   freebsd|netbsd|darwin)
@@ -486,6 +508,8 @@ fi
 
 if [ -n "$docker_cmd" ]; then
   "$docker_cmd" run                                       \
+    -e docker_cmd="$docker_cmd"                           \
+    -e docker_image="$docker_image"                       \
     -e gitstatus_kernel="$gitstatus_kernel"               \
     -e gitstatus_arch="$gitstatus_arch"                   \
     -e gitstatus_cpu="$gitstatus_cpu"                     \
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/mbuild b/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/mbuild
--- a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/mbuild
+++ b/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/mbuild
@@ -117,6 +117,7 @@ local -rA assets=(
   linux-armv6l           build-linux-armv7l
   linux-armv7l           build-linux-armv7l
   linux-i686             build-linux-x86_64
+  linux-ppc64le          build-linux-ppc64le
   linux-x86_64           build-linux-x86_64
 )
 
@@ -151,7 +152,7 @@ done
 
 shift $((OPTIND - 1))
 
-(( $# )) || set -- ${(k)assets}
+(( $# )) || set -- ${(ko)assets}
 set -- ${(u)@}
 
 local platform
@@ -180,14 +181,15 @@ local build='
 function build-unix() {
   local intro flags=(-sw)
   case $2 in
-    darwin-*) intro='PATH="/usr/local/bin:$PATH"';;
+    linux-ppc64le);;
     linux-*)  flags+=(-d docker);;
+    darwin-*) intro='PATH="/usr/local/bin:$PATH"';;
   esac
   ssh $1 -- /bin/sh -uex <<<"
     $intro
     cd /tmp
     $build ${2##*-} ${(j: :)${(@q)flags}}"
-  scp $1:/tmp/gitstatus/usrbin/gitstatusd-$2 $binaries/
+  scp $1:/tmp/gitstatus/usrbin/gitstatusd $binaries/gitstatusd-$2
 }
 
 function build-windows() {
@@ -200,15 +202,22 @@ function build-windows() {
 
   local tmp env bin intro flags=(-w)
   case $2 in
-    msys_nt-10.0-i686)     bin='msys32/usr/bin';|
-    msys_nt-10.0-x86_64)   bin='msys64/usr/bin';|
     cygwin_nt-10.0-i686)   bin='cygwin32/bin'  ;|
     cygwin_nt-10.0-x86_64) bin='cygwin64/bin'  ;|
+    msys_nt-10.0-i686)     bin='msys32/usr/bin';|
+    msys_nt-10.0-x86_64)   bin='msys64/usr/bin';|
+    cygwin_nt-10.0-*)
+      tmp='/cygdrive/c/tmp'
+    ;|
     msys_nt-10.0-*)
       flags+=(-s)
       tmp='/c/tmp'
       env='MSYSTEM=MSYS'
+      intro='pacman -Syu --noconfirm; pacman -S --needed --noconfirm git; '
+      intro+='PATH="$PATH:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"'
       while true; do
+        # TODO: run autorebase only when getting an error that can be fixed by autorebasing.
+        break
         local out
         out="$(ssh $1 cmd.exe "$c/${bin%%/*}/autorebase.bat" 2>&1)"
         [[ $out == *"The following DLLs couldn't be rebased"* ]] || break
@@ -229,7 +238,7 @@ function build-windows() {
             while true; do
               IFS= read -u $fd -r line || return 0
               if [[ $line == *"warning: terminate MSYS2"* ]]; then
-                # At this point the machine is hosed. Rogue process with corrupted name
+                # At this point the machine is hosed. A rogue process with a corrupted name
                 # is eating all CPU. The top SSH connection won't terminate on its own.
                 ssh $1 powershell.exe <<<'Restart-Computer -Force' || true
                 sleep 30
@@ -243,12 +252,7 @@ function build-windows() {
           }
         done
       } "$@"
-      intro='pacman -Syu --noconfirm; pacman -S --needed --noconfirm git; '
-      intro+='PATH="$PATH:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"'
-    ;;
-    cygwin_nt-10.0-*)
-      tmp='/cygdrive/c/tmp'
-    ;;
+    ;|
   esac
 
   ssh $1 $c/$bin/env.exe $env c:/$bin/bash.exe -l <<<"
@@ -258,7 +262,7 @@ function build-windows() {
     cd -- $tmp
     $build ${2##*-} ${(j: :)${(@q)flags}}
     exit"
-  scp $1:$c/tmp/gitstatus/usrbin/gitstatusd-$2 $binaries/
+  scp $1:$c/tmp/gitstatus/usrbin/gitstatusd $binaries/gitstatusd-$2
   chmod +x $binaries/gitstatusd-$2
 }
 
@@ -270,7 +274,7 @@ function build() (
   zsystem flock $locks/$machine
   build-${protocol[(k)$platform]} $machine $platform
   local tmp=gitstatusd-$platform.tmp.$$.tar.gz
-  ( cd -q -- $binaries; GZIP=-9 tar -czf $tmp gitstatusd-$platform )
+  ( cd -q -- $binaries; tar --owner=0 --group=0 -I 'gzip -9' -cf $tmp gitstatusd-$platform )
   mv -f -- $binaries/$tmp $binaries/gitstatusd-$platform.tar.gz
 )
 
@@ -281,17 +285,24 @@ function mbuild() {
     print -r -- "starting build for $platform on $assets[$platform] (pid $!)"
     pids+=($platform $!)
   done
+  local failed=()
   for platform pid in $pids; do
     print -rn -- "$platform => "
     if wait $pid; then
       print -r -- "ok"
     else
-      print -r -- "error $?"
-      print -r -- "---------------------"
-      >&2 cat $logs/$platform
-      return 1
+      print -r -- "error"
+      failed+=$platform
     fi
   done
+  (( $#failed )) || return 0
+  print
+  print -r -- "Error logs:"
+  print
+  for platform in $failed; do
+    print -r -- "  $platform => $logs/$platform"
+  done
+  return 1
 }
 
 # Copied from https://github.com/romkatv/run-process-tree.
